# Generated by Django 3.2.5 on 2021-07-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_learning', '0003_logtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtransaction',
            old_name='acount',
            new_name='account',
        ),
    ]
