# Generated by Django 3.2.5 on 2021-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_learning', '0004_rename_acount_logtransaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
